repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: debug-statements
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-json
    - id: check-xml
    - id: detect-private-key
    - id: check-ast
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
