version: '3.4'

services:

  influxdb:
    image: influxdb:1.8.10
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - influxdb_data:/var/lib/influxdb

#---------------------------
  sl2raspberryshake:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - influxdb
    environment:
      - INFLUXDB_PORT_8086_TCP_ADDR=influxdb
      - INFLUXDB_PORT_8086_TCP_PORT=8086
      - SEEDLINK_SERVER=rs.local
      - FDSN_WS_STATION_SERVER=https://fdsnws.raspberryshakedata.com
      # do not put space into SEEDLINK_STREAMS string !
      - SEEDLINK_STREAMS=[('AM','.*','.*','.*')]
      - FLUSHTIME=5
      - DB_NAME=raspberryshake
      - KEEP=1
      - RECOVER="no"
      - EXTRA='--drop-db'

  sl2generic:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - influxdb
    environment:
      - INFLUXDB_PORT_8086_TCP_ADDR=influxdb
      - INFLUXDB_PORT_8086_TCP_PORT=8086
      - SEEDLINK_SERVER=10.0.1.36
      - FDSN_WS_STATION_SERVER=http://10.0.1.36:8080
      # do not put space into SEEDLINK_STREAMS string !
      - SEEDLINK_STREAMS=[('1T','.*','HHZ','.*'),('QM','.*','HHZ','.*'),('MT','.*','(HHZ|DHZ)','.*'),('FR','.*','(HHZ|EHZ|ELZ)','.*'),('AM','.*','(SHZ|EHZ)','.*'),('ND','.*','HHZ','.*'),('CL','.*','HHZ','.*'),('FR','.*','SHZ',''),('RA','.*','HNZ','00'),('RD','.*','BHZ','.*'),('G','.*','BHZ','.*'),('XX','.*','BHZ','.*'),('(SZ|RT|IG|RG)','.*','.*Z','.*')]
      - DB_NAME=eost
      - KEEP=1
      - RECOVER="yes"
      # - EXTRA='--drop-db'

  sl2local:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - influxdb
    environment:
      - INFLUXDB_PORT_8086_TCP_ADDR=influxdb
      - INFLUXDB_PORT_8086_TCP_PORT=8086
      - SEEDLINK_SERVER=host.docker.internal
      - SEEDLINK_PORT=10002
      - FDSN_WS_STATION_SERVER=http://host.docker.internal:10003
      # do not put space into SEEDLINK_STREAMS string !
      - SEEDLINK_STREAMS=[('1T','.*','HHZ','.*'),('QM','.*','HHZ','.*'),('MT','.*','(HHZ|DHZ)','.*'),('FR','.*','(HHZ|EHZ|ELZ)','.*'),('AM','.*','(SHZ|EHZ)','.*'),('ND','.*','HHZ','.*'),('CL','.*','HHZ','.*'),('FR','.*','SHZ',''),('RA','.*','HNZ','00'),('RD','.*','BHZ','.*'),('G','.*','BHZ','.*'),('XX','.*','BHZ','.*'),('(SZ|RT|IG|RG)','.*','.*Z','.*')]
      - DB_NAME=eost
      - KEEP=1
      - RECOVER="yes"
      # - EXTRA='--drop-db'



#---------------------------

  grafana:
    image: grafana/grafana:8.4.3
    ports:
      - 3000:3000
    volumes:
      - grafana_conf:/etc/grafana
      - grafana_data:/var/lib/grafana
      - ./dashboard:/var/lib/grafana/dashboards:rw
      - ./provisioning:/etc/grafana/provisioning
    links:
      - influxdb
      #- sl2local
      - sl2generic
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel,neocat-cal-heatmap-panel



  rshakegrafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
    volumes:
      - grafana_conf_rshake:/etc/grafana
      - grafana_data_rshake:/var/lib/grafana
      - ./dashboard:/var/lib/grafana/dashboards:rw
      - ./rshake_provisioning:/etc/grafana/provisioning
    links:
      - influxdb
      - sl2raspberryshake
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel,neocat-cal-heatmap-panel

#---------------------------

volumes:
  influxdb_data:
    name: sl2influxdb_influxdb_data
  grafana_data:
    name: sl2influxdb_grafana_data
  grafana_conf:
    name: sl2influxdb_grafana_conf
  grafana_data_rshake:
    name: sl2influxdb_grafana_data_rshake
  grafana_conf_rshake:
    name: sl2influxdb_grafana_conf_rshake
