version: '3.4'

services:

  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - influxdb_data:/var/lib/influxdb

#---------------------------

  sl2raspberryshake:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - influxdb
    environment:
      - INFLUXDB_PORT_8086_TCP_ADDR=influxdb
      - INFLUXDB_PORT_8086_TCP_PORT=8086
      - SEEDLINK_SERVER=raspberryshake.local
      - FDSN_WS_STATION_SERVER=http://raspberryshake.net:8080
      # do not put space into SEEDLINK_STREAMS string !
      - SEEDLINK_STREAMS=[('AM','.*','.*','.*')]
      - FLUSHTIME=5
      - DB_NAME=raspberryshake
      - KEEP=1
      - RECOVER="no"
      - EXTRA='--drop-db'

  sl2generic:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - influxdb
    environment:
      - INFLUXDB_PORT_8086_TCP_ADDR=influxdb
      - INFLUXDB_PORT_8086_TCP_PORT=8086
      - SEEDLINK_SERVER=renass-fw.u-strasbg.fr
      - FDSN_WS_STATION_SERVER=http://renass-sc1.u-strasbg.fr:8080
      # do not put space into SEEDLINK_STREAMS string !
      - SEEDLINK_STREAMS=[('FR','.*','(HHZ|EHZ|ELZ)','.*'),('AM','.*','(SHZ|EHZ)','.*'),('ND','.*','HHZ','.*'),('CL','.*','HHZ','.*'),('FR','.*','SHZ',''),('RA','.*','HNZ','00'),('RD','.*','BHZ','.*'),('G','.*','BHZ','.*'),('XX','.*','BHZ','.*'),('(SZ|RT|IG|RG)','.*','.*Z','.*')]
      - DB_NAME=eost
      - KEEP=1
      - RECOVER="yes"
      # - EXTRA='--drop-db'

#---------------------------

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_conf:/etc/grafana
      - grafana_data:/var/lib/grafana
      - ../dashboard:/var/lib/grafana/dashboards:rw
      - ./provisioning:/etc/grafana/provisioning
    links:
      - influxdb
      - sl2generic
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel 0.1.0,neocat-cal-heatmap-panel

  rshakegrafana:
    image: grafana/grafana:master
    ports:
      - 3001:3000
    volumes:
      - grafana_conf_rshake:/etc/grafana
      - grafana_data_rshake:/var/lib/grafana
      - ../dashboard:/var/lib/grafana/dashboards:rw
      - ./rshake_provisioning:/etc/grafana/provisioning
    links:
      - influxdb
      - sl2raspberryshake
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel 0.1.0,neocat-cal-heatmap-panel

#---------------------------

volumes:
  influxdb_data:
    external:
      name: sl2influxdb_influxdb_data
  grafana_data:
    name: sl2influxdb_grafana_data
  grafana_conf:
    name: sl2influxdb_grafana_conf
  grafana_data_rshake:
    name: sl2influxdb_grafana_data_rshake
  grafana_conf_rshake:
    name: sl2influxdb_grafana_conf_rshake
