version: '2'

services:

  influxdb:
    image: influxdb
    ports:
      - 8086:8086
      - 8083:8083

  sl2influxdb:
    build: 
      context: .
      dockerfile: Dockerfile
    links:
      - influxdb
    environment:
      - INFLUXDB_PORT_8086_TCP_ADDR=influxdb
      - INFLUXDB_PORT_8086_TCP_PORT=8086
      - SEEDLINK_SERVER=10.0.0.15
      - DB_NAME=eost
      - KEEP=7
      - RECOVER=yes
      #- EXTRA='--drop-db'

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
