apiVersion: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
- name: influxdb
  type: influxdb
  access: proxy
  orgId: 1
  url: http://influxdb:8086
  basicAuth: true
  basicAuthUser: admin
  basicAuthPassword: admin
  database: eost
  isDefault: true
  version: 1
  editable: true
